### ISSUE TITLE
why do you use ZeroMQ

### ISSUE THREAD

**Issue by HoangNgo88** [egecetin/Repo-Init#50]
Hi, I am reading your project and I love this project
I have a question, why do you choose ZeroMQ in your project instead of others like RabbitMQ or Kafka, are there any special feature but others dont have it. Can you share me about it. I am wondering when I should choose ZeroMQ instead of others like RabbitMQ or Kafka

**Comment by egecetin** [comment]
To be honest it just depends on the decision about where you want to use.

Both ZeroMQ and RabbitMQ (or Kafka) are reliable and fast enough for most of the applications. Where the ZeroMQ differs is, only the message throughput. Since the ZeroMQ does not have an application in the middle (it uses direct socket connection between applications) when the throughput goes up ZeroMQ catches the performance requirements more easily. Direct connection = there is no extra processing in the middle.

Another difference is ZeroMQ's `inproc` connection type. Where you needed you can transfer information between threads using ZeroMQ connections without trouble.

This is why I chose ZeroMQ for my template, most of time I design _applications talk with only one other on same hardware and uses thread workers inside application_ (think like you have service receiving messages than asks the authentication service and waits for reply OK or UNAUTH then pushes payload to a worker). Since,

- You are in same hardware reliability is not a big concern unless your CPU is not burning :)
- The functions future instructions, depends on the reply of sent messages (the user is known or not so drop message or process) so fast and simple connection to reduce delay is better

This is my case, so I chose the ZeroMQ.

But for RabbitMQ and Kafka you can configure more advanced patterns. I used Kafka before for example for a more distributed pattern, N computers sends data to one central computer so, for endpoints there is no huge workload but for center there is a trouble 😀. Lots of messages rushing to the center. This is Kafka's advantage; you can easily scale your central application to handle more workload with its workers/clusters. Also since there is a middle application (Kafka's itself) the packet loss is less likely (I mean preventable, it can resend/retransmit better than ZeroMQ).

**Comment by egecetin** [comment]
@HoangNgo88 I'm closing the issue for now. If you have any other questions or comments, I'd be happy to answer them.
